// Mocks generated by Mockito 5.0.16 from annotations
// in weathersdbx/test/widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weathersdbx/app/app_mgr.dart' as _i2;
import 'package:weathersdbx/data/data_model.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AppMgr].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppMgr extends _i1.Mock implements _i2.AppMgr {
  MockAppMgr() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic initAppMgr({_i2.StorageMgr? storageMgr}) => super
      .noSuchMethod(Invocation.method(#initAppMgr, [], {#dataMgr: storageMgr}));
  @override
  dynamic setCurrentLocationStationId(String? stationId) => super.noSuchMethod(
      Invocation.method(#setCurrentLocationStationId, [stationId]));
  @override
  _i3.Future<_i4.CurrentObservation?> fetchCurrentObservation() =>
      (super.noSuchMethod(Invocation.method(#fetchCurrentObservation, []),
              returnValue: Future<_i4.CurrentObservation?>.value())
          as _i3.Future<_i4.CurrentObservation?>);
  @override
  String toString() => super.toString();
}
